### ISSUE TITLE
Include an option to use OpenStreetMap (OSM) instead of GoogleMaps

### ISSUE THREAD

**Issue by tobymutz** [foucdeg/x-plane-map-electron#19]
Hello again.

I really enjoy using your excellent app whenever I'm flying on X-Plane 11 or even X-Plane 10 (still) in conjunction with seeing where I am (virtually) on GoogleMaps.

However when using the app and starting at an airport, especially a large one like LFPG or LEMD or EGLL, you cannot see the names of the taxiways, runways or gate positions on GoogleMaps, unlike OpenStreetMap which shows this extra level of detail which is extremely useful for following virtual ATC instructions to taxi to/from the gate and the runway.

So I would like to suggest a modification of your app by including options to use either GoogleMaps or OpenStreetMap. I hope there will not be licensing issues with incorporating OSM into your app or too many technical barriers to making this suggested modification.

In addition, I would also like to suggest using the aircraft heading dataref to indicate the direction an aircraft is facing when not moving or stationary at a gate or ramp. Currently the app only shows the correct heading when the aircraft is moving.

I would like to know what you think.

Many thanks for your continued good work.

**Comment by foucdeg** [comment]
Hello Toby,

Regarding the heading dataref, I remember you suggested it. My issue is that I need to implement a fallback mechanism so that when the user provides the dataref, the heading is used, and when they don't, it's calculated. So it's not that easy. I'm currently working on a replay feature.

Regarding OSM, I always thought the OSM maps didn't look so good, so I used a hacky way to have Google Maps tiles. But you just gave me a good reason to use OSM: the taxiways! I only just saw this today, it's so cool to see them all at LFPG. Much more practical than the PDF chart :) On top of that, the free version of Google Maps just became much more restricted and I'm afraid to hit the top of the free tier.

So I'm actually thinking of just switching to OSM. Can you see any reason not to?

**Comment by foucdeg** [comment]
@tobymutz OSM made it into version 2.5.0. Feel free to get the update :)
